### ISSUE TITLE
api still bans you

### ISSUE THREAD

**Issue by DWAA1660** [ALittlePatate/Discord-Invite-Generator#1]
it still bans you you may need to be lowered to 40 requests or something

**Comment by ALittlePatate** [comment]
Yeah maybe, that's a dead project ngl, but you can add it yourself and make a Pull Request :)

**Comment by DWAA1660** [comment]
> Yeah maybe, that's a dead project ngl, but you can add it yourself and make a Pull Request :)
I cant find where it says it does 50 do you mind showing me where it is and how to change it
